---
# tasks file for roles/webserver
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  
- name: Add custom web page
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ nginx_web_path }}/index.html"
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx
